name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'  # ou utilisez '20' si vous préférez la version 20 de Node.js
      - run: yarn install
      - run: yarn test
